"""Removendo as tabelas contratos e funcionarios_contratos

Revision ID: 0910701fa454
Revises: 3cbf57ac877b
Create Date: 2025-01-09 00:13:39.841714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0910701fa454'
down_revision = '3cbf57ac877b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios_contrato')
    op.drop_table('contratos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios_contrato',
    sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contrato_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], name='funcionarios_contrato_contrato_id_fkey'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name='funcionarios_contrato_funcionario_id_fkey'),
    sa.PrimaryKeyConstraint('funcionario_id', 'contrato_id', name='funcionarios_contrato_pkey')
    )
    op.create_table('contratos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vigencia_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('vigencia_fim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('numero_funcionarios', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='contratos_empresa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contratos_pkey')
    )
    # ### end Alembic commands ###
