"""empty message

Revision ID: 16dd188571a9
Revises: 3d0ef6e9921e
Create Date: 2025-01-28 11:14:38.621162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16dd188571a9'
down_revision = '3d0ef6e9921e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades_limpeza', schema=None) as batch_op:
        batch_op.drop_column('data_horario_fim')
        batch_op.drop_column('data_horario_inicio')

    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atividade_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('horario_inicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('horario_fim', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'atividades_limpeza', ['atividade_id'], ['id'])
        batch_op.drop_column('data_hora_criacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('observacao')
        batch_op.drop_column('horario_fim')
        batch_op.drop_column('horario_inicio')
        batch_op.drop_column('atividade_id')

    with op.batch_alter_table('atividades_limpeza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_horario_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('data_horario_fim', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
