"""empty message

Revision ID: 3cbf57ac877b
Revises: c0a7b5444ac4
Create Date: 2025-01-03 22:05:59.199719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbf57ac877b'
down_revision = 'c0a7b5444ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.alter_column('supervisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.alter_column('supervisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
