"""Atualizando as tabelas

Revision ID: 422d55dc5fec
Revises: 
Create Date: 2024-12-01 12:20:51.292662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422d55dc5fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambientes', schema=None) as batch_op:
        batch_op.alter_column('localizacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('atividades_limpeza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'FINALIZADO', name='statuslimpeza'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades_limpeza', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('ambientes', schema=None) as batch_op:
        batch_op.alter_column('localizacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
