"""Criar tabela de relatórios

Revision ID: 77318d7bbad5
Revises: f8e02a113ce0
Create Date: 2024-12-24 12:00:05.314439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77318d7bbad5'
down_revision = 'f8e02a113ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorios')
    # ### end Alembic commands ###
