"""Removendo a tabela de historicos de solicitações

Revision ID: 7becd6bfd798
Revises: 0910701fa454
Create Date: 2025-01-16 12:36:23.333498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7becd6bfd798'
down_revision = '0910701fa454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_solicitacoes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_solicitacoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('solicitacao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funcionario_origem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funcionario_destino_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_movimentacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('descricao_movimentacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['funcionario_destino_id'], ['funcionarios.id'], name='historico_solicitacoes_funcionario_destino_id_fkey'),
    sa.ForeignKeyConstraint(['funcionario_origem_id'], ['funcionarios.id'], name='historico_solicitacoes_funcionario_origem_id_fkey'),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], name='historico_solicitacoes_solicitacao_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historico_solicitacoes_pkey')
    )
    # ### end Alembic commands ###
