"""empty message

Revision ID: 957d0e1149d4
Revises: 6eb3a45c2c6a
Create Date: 2025-01-22 12:21:39.000084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957d0e1149d4'
down_revision = '6eb3a45c2c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('solicitacoes_setor_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'funcionarios', ['admin_id'], ['id'])
        batch_op.drop_column('setor_admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor_admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('solicitacoes_setor_admin_id_fkey', 'funcionarios', ['setor_admin_id'], ['id'])
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
