"""empty message

Revision ID: c0a7b5444ac4
Revises: b081612802af
Create Date: 2025-01-03 17:42:13.854452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a7b5444ac4'
down_revision = 'b081612802af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades_limpeza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitacao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'solicitacoes', ['solicitacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades_limpeza', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('solicitacao_id')

    # ### end Alembic commands ###
