"""empty message

Revision ID: d1592eed911e
Revises: 
Create Date: 2024-12-30 15:29:20.405400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1592eed911e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('contato', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('tipos_funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vigencia_inicio', sa.DateTime(), nullable=False),
    sa.Column('vigencia_fim', sa.DateTime(), nullable=False),
    sa.Column('numero_funcionarios', sa.Integer(), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atividades_limpeza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_horario_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_horario_fim', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'FINALIZADO', name='statuslimpeza'), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios_contrato',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('funcionario_id', 'contrato_id')
    )
    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANALISE', 'ENVIADO_SUPERVISOR', 'FINALIZADO', name='statussolicitacao'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_finalizacao', sa.DateTime(), nullable=True),
    sa.Column('setor_admin_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setor_admin_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_origem_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_destino_id', sa.Integer(), nullable=True),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=False),
    sa.Column('descricao_movimentacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_destino_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['funcionario_origem_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_solicitacoes')
    op.drop_table('solicitacoes')
    op.drop_table('relatorios')
    op.drop_table('funcionarios_contrato')
    op.drop_table('atividades_limpeza')
    op.drop_table('funcionarios')
    op.drop_table('contratos')
    op.drop_table('tipos_funcionarios')
    op.drop_table('empresas')
    op.drop_table('ambientes')
    # ### end Alembic commands ###
