"""empty message

Revision ID: d66eadddbdb4
Revises: 3aadf5ec844b
Create Date: 2025-02-04 22:08:58.083679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66eadddbdb4'
down_revision = '3aadf5ec844b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades_limpeza', schema=None) as batch_op:
        batch_op.drop_constraint('atividades_limpeza_solicitacao_id_fkey', type_='foreignkey')
        batch_op.drop_column('solicitacao_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades_limpeza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitacao_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('atividades_limpeza_solicitacao_id_fkey', 'solicitacoes', ['solicitacao_id'], ['id'])

    # ### end Alembic commands ###
