"""Correção de nomes

Revision ID: e5d89fe362fe
Revises: 422d55dc5fec
Create Date: 2024-12-01 12:30:40.389139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d89fe362fe'
down_revision = '422d55dc5fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambientes', schema=None) as batch_op:
        batch_op.alter_column('localizacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambientes', schema=None) as batch_op:
        batch_op.alter_column('localizacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
